### PR TITLE
fix: traverse all the child cmds + duplicates

### LINKED ISSUE #95: Duplicate errors on running validator
## Description
Running Validator package on rhoas CLI as unit test doesn't give desired output. The errors are duplicated and all the descendant commands are not traversed. 

### Steps to reproduce
Run this validator in a unit test in rhoas CLI
I copied the code for validator package in rhoas

### Expected vs actual behaviour
Duplicate errors are arising, and all the subcommands are not traversed

### Logs

```bash
$ go test ./pkg/cmd/root/

--- FAIL: Test_ExecuteCommand (0.01s)
    root_test.go:51: LENGTH_RULE: cmd rhoas: Short length should be at least 15
    root_test.go:51: LENGTH_RULE: cmd rhoas: Long length should be at least 100
    root_test.go:51: LENGTH_RULE: cmd rhoas: Short length should be at least 15
    root_test.go:51: LENGTH_RULE: cmd rhoas: Long length should be at least 100
    root_test.go:51: LENGTH_RULE: cmd rhoas cluster: Long length should be at least 100
    root_test.go:51: MUST_EXIST_RULE: cmd rhoas cluster: Long must be present
    root_test.go:51: LENGTH_RULE: cmd rhoas: Short length should be at least 15
    root_test.go:51: LENGTH_RULE: cmd rhoas: Long length should be at least 100
    root_test.go:51: LENGTH_RULE: cmd rhoas cluster: Long length should be at least 100
    root_test.go:51: MUST_EXIST_RULE: cmd rhoas cluster: Long must be present
FAIL
FAIL    github.com/redhat-developer/app-services-cli/pkg/cmd/root       0.022s
FAIL
```

### PR DESCRIPTION
**Pull request by ankithans**
Closes #95  

### Description
Fixes duplicate errors and traverse all the subcommands

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist

- [x] Duplication of validation errors
- [x] Traverse all the subcommands

## Screenshots (if appropriate):

### CODE REVIEW

**Comment by ankithans** [comment]
https://github.com/aerogear/charmil/blob/ankithans/issue95/validator/example/cmd.go 
```
cmd
  cmd3
  cmd1
     cmd2
```
Here only cmd, cmd1, cmd2 are traversed. **cmd3 is skipped!** Checked with rhoas similar issue is persisting. Fixed the duplicate validation error. Trying to solve this error

File: validator/rules/executor.go [hunk 1]
```diff
@@ -30,16 +31,35 @@ func (config *RuleConfig) ExecuteRules(cmd *cobra.Command) []validator.Validatio
...
-			return info.Errors
-		},
-	)
+	lenErrs := validateLength(cmd, config.Length, config.Verbose)
+	info.TotalErrors += len(lenErrs)
+
+	mustExistErrs := validateMustExist(cmd, config.MustExist, config.Verbose)
+	info.TotalErrors += len(mustExistErrs)
+
+	info.Errors = append(info.Errors, lenErrs...)
```
Comment (wtrocki) [inline validator/rules/executor.go:40]: we should create method that does validate and add errorz for generic rule

File: validator/rules/executor.go [hunk 2]
```diff
@@ -30,16 +31,35 @@ func (config *RuleConfig) ExecuteRules(cmd *cobra.Command) []validator.Validatio
...
+	info.TotalTested++
+
+	for _, child := range cmd.Commands() {
+
+		// base case
+		if !child.IsAvailableCommand() || child.IsAdditionalHelpTopicCommand() {
+			continue
+		}
+
+		// recursive call
```
Comment (wtrocki) [inline validator/rules/executor.go:51]: This is not Add verbose logger here

File: validator/rules/executor.go [hunk 3]
```diff
@@ -30,16 +31,35 @@ func (config *RuleConfig) ExecuteRules(cmd *cobra.Command) []validator.Validatio
...
+		if err := config.executeHelper(child, info); err != nil {
+			return err
+		}
+	}
+
+	// prints additional info in debug mode
+	if config.Verbose {
+		fmt.Printf("commands checked: %d\nchecks failed: %d\n", info.TotalTested, info.TotalErrors)
```
Comment (wtrocki) [inline validator/rules/executor.go:59]: This is not verbose. It should be printed normally but to stderr

**Comment by ankithans** [comment]
This was hard to debug, but got the desired output. Basically, It was a recursion problem 😄. issue #95 resolved
```bash
$ go test ./validator/example/
--- FAIL: Test_ExecuteCommand (0.00s)
    cmd_test.go:20: LENGTH_RULE: cmd cmd0: Long length should be at least 100
    cmd_test.go:20: LENGTH_RULE: cmd cmd0: Example length should be at least 100
    cmd_test.go:20: LENGTH_RULE: cmd cmd0 subcmd01 subcmd12: Short length should be at least 15
    cmd_test.go:20: LENGTH_RULE: cmd cmd0 subcmd01 subcmd12: Long length should be at least 100
    cmd_test.go:20: LENGTH_RULE: cmd cmd0 subcmd01 subcmd12: Example length should be at least 100
    cmd_test.go:20: MUST_EXIST_RULE: cmd cmd0 subcmd01 subcmd12: Short must be present
    cmd_test.go:20: MUST_EXIST_RULE: cmd cmd0 subcmd01 subcmd12: Long must be present
    cmd_test.go:20: LENGTH_RULE: cmd cmd0 subcmd01: Short length should be at least 15
    cmd_test.go:20: LENGTH_RULE: cmd cmd0 subcmd01: Long length should be at least 100
    cmd_test.go:20: LENGTH_RULE: cmd cmd0 subcmd01: Example length should be at least 100
    cmd_test.go:20: MUST_EXIST_RULE: cmd cmd0 subcmd01: Short must be present
    cmd_test.go:20: MUST_EXIST_RULE: cmd cmd0 subcmd01: Long must be present
    cmd_test.go:20: LENGTH_RULE: cmd cmd0 subcmd03: Short length should be at least 15
    cmd_test.go:20: LENGTH_RULE: cmd cmd0 subcmd03: Long length should be at least 100
    cmd_test.go:20: LENGTH_RULE: cmd cmd0 subcmd03: Example length should be at least 100
    cmd_test.go:20: MUST_EXIST_RULE: cmd cmd0 subcmd03: Short must be present
    cmd_test.go:20: MUST_EXIST_RULE: cmd cmd0 subcmd03: Long must be present
FAIL
FAIL    github.com/aerogear/charmil/validator/example   0.152s
FAIL
```

File: validator/example/cmd.go [hunk 4]
```diff
@@ -17,21 +17,29 @@ func NewCommand() *cobra.Command {
 	}
 
 	cmd1 := &cobra.Command{
-		Use:     "subcmd",
+		Use:     "subcmd01",
```
Comment (wtrocki) [inline validator/example/cmd.go:20]: Do you mind to use for loops for creating commands.
It will look better without DRY

File: validator/rules/executor.go [hunk 5]
```diff
@@ -25,21 +25,67 @@ func (config *RuleConfig) ExecuteRules(cmd *cobra.Command) []validator.Validatio
...
+			continue
+		}
+
+		// recursive call
+		info.Errors = config.executeHelper(child, info)
+
+	}
+
+	// prints additional info in debug mode
+	if config.Verbose {
```
Comment (wtrocki) [inline validator/rules/executor.go:66]: Lets remove verbose check and use sdterr (

File: validator/rules/executor.go [hunk 6]
```diff
@@ -25,21 +25,67 @@ func (config *RuleConfig) ExecuteRules(cmd *cobra.Command) []validator.Validatio
...
+	info.Errors = config.executeRulesChildren(cmd, info)
+
+	return info.Errors
+}
+
+// validate returns validation errors by executing the rules
+func (config *RuleConfig) validate(cmd *cobra.Command, info *validator.StatusLog) {
+
+	// Length rule
+	lenErrs := validateLength(cmd, config.Length, config.Verbose)
```
Comment (wtrocki) [inline validator/rules/executor.go:79]: Lets use for loop for processing rules rather than calling each rule

**Review by wtrocki — APPROVED** [review]
Lets push this to rhoas but address my comments

File: validator/rules/executor.go (hunk 6 above)
Comment (ankithans) [reply validator/rules/executor.go]: @wtrocki I have addressed above 2 comments. As all rules gives different function to execute, how can I use them in loop?
like length - validateLength
MustExist - validateMustExist

And rule config also looks something like this
```go
type RuleConfig struct {
	Verbose bool
	Length
	MustExist
}
```
Can you suggest some way?

**Comment by wtrocki** [comment]
lets release.

> Can you suggest some way?

we should have the same interface and can the same function. Without that there will be no way to add rule to validator. Create issue for this. This two methods should be the same method
